version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    ports:
      - 6379:6379

  owner-service:
    build: ./owner-service
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongo:27017/ownerdb

  products-service:
    build: ./products-service
    ports:
      - 3002:3002
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongo:27017/productsdb

  order-service:
    build: ./order-service
    ports:
      - 3003:3003
    depends_on:
      - mongo
      - rabbitmq
      - redis
    environment:
      MONGO_URI: mongodb://mongo:27017/orderdb
      REDIS_URL: redis://redis:6379
